/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminFaqRouteImport } from './routes/admin/faq'
import { Route as AdminFeaturesRouteImport } from './routes/admin/features'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminRefundsRouteImport } from './routes/admin/refunds'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesAbatRouteImport } from './routes/courses.abat'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin/courses.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesAbatRoute = CoursesAbatRouteImport.update({
  id: '/abat',
  path: '/abat',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AdminCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/faq': typeof AdminFaqRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/courses/abat': typeof CoursesAbatRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/faq': typeof AdminFaqRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/courses/abat': typeof CoursesAbatRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/faq': typeof AdminFaqRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/courses/abat': typeof CoursesAbatRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/pricing'
    | '/refund-policy'
    | '/resources'
    | '/services'
    | '/shop'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/faq'
    | '/admin/features'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/courses/abat'
    | '/admin/'
    | '/courses/'
    | '/admin/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/pricing'
    | '/refund-policy'
    | '/resources'
    | '/services'
    | '/shop'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/faq'
    | '/admin/features'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/courses/abat'
    | '/admin'
    | '/courses'
    | '/admin/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/pricing'
    | '/refund-policy'
    | '/resources'
    | '/services'
    | '/shop'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/faq'
    | '/admin/features'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/refunds'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/courses/abat'
    | '/admin/'
    | '/courses/'
    | '/admin/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  PricingRoute: typeof PricingRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/abat': {
      id: '/courses/abat'
      path: '/abat'
      fullPath: '/courses/abat'
      preLoaderRoute: typeof CoursesAbatRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminFaqRoute: typeof AdminFaqRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminFaqRoute: AdminFaqRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesAbatRoute: typeof CoursesAbatRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesAbatRoute: CoursesAbatRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  PricingRoute: PricingRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
